[package]
name = "block-breaker-tui"
version = "0.1.0"
authors = ["Jeffas <dev@jeffas.io>"]
edition = "2018"

[dependencies]
block-breaker = "0.1.0"
crossterm = "0.9.6"

[dependencies.tui]
version = "0.6.1"
default-features = false
features = ["crossterm"]
